// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtmwyzrleyevcgtfwrnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0bXd5enJsZXlldmNndGZ3cm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDM3NDcsImV4cCI6MjA2NTU3OTc0N30.a2c2V2HbnTqN4K87uATCYawD_NmOYBEyYE7VveLc2dk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);