// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmedezpygwzpqzsibkcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtZWRlenB5Z3d6cHF6c2lia2NjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTU5ODQsImV4cCI6MjA2NTM3MTk4NH0.Rj6x_tI27AqVfiikUX8ICgveRJassi14YphCg6ZG4LI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);